export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';

export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';